### ISSUE TITLE
a_puzzle

### ISSUE THREAD

**Issue by shlff** [jstac/continuous_time_mcs#10]
Dear @jstac , I have a question about the ``s`` of ``(N_r)_{r\leq s}`` in subsection [The Restarting Property](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/poisson.md#uniqueness) in lecture ``poisson``:
- will ``(N_{s+t} - N_s)_{t \geq 0}`` be dependent of the Poisson process``(N_r)_{r \geq 0}``, if ``r`` can take values greater than ``s``?

**Comment by jstac** [comment]
Hi @shlff, the answer is yes.  If `r` can take values larger than `s`, that gives us useful information about the increment.

**Comment by shlff** [comment]
Thanks @jstac . Can I understand like this:
- if ``r`` can take values larger than ``s``, then ``(N_r)`` will play a role in constructing the process ``(N_{s+t} - N_s)_{t \geq 0}``.
- For example, ``M_t = N_{t + s} - N_s``, where ``t = r - s``.

**Comment by jstac** [comment]
Try thinking about it like this:

`N_t` is the number of customers that have arrived by time `t`.

If I know that 2 customers have arrived by time `r=10`, that helps me predict how many will arrive between `s=5` and `t=15`.

**Comment by shlff** [comment]
Got it, thank @jstac . Your example is very helpful! I will close this issue.
