### ISSUE TITLE
[ergodicity] an issue in solution 2

### ISSUE THREAD

**Issue by shlff** [jstac/continuous_time_mcs#82]
Dear @jstac , as I mentioned in PR #81 , there is an issue in the [solution 2's proof of lecture ergodicity](https://github.com/jstac/continuous_time_mcs/blob/master/ctmc_lectures/ergodicity.md#exercises), even after fixing.

In Exercise 2, we want to prove that the Markov semigroup $(P_t)$ with intensity $$Q=\begin{pmatrix} -\lambda_0 & \lambda_0 & 0 & 0 & \cdots \\ 0 & -\lambda_1 & \lambda_1 & 0 & \cdots \\ 0 & 0 & -\lambda_2 & \lambda_2 & \cdots\\ \vdots & \vdots & \vdots & \vdots & \ddots \end{pmatrix}$$ has no stationary distribution.

After fixing, we have for any $j \geq 1$,
- $(\phi Q)(j) = \sum_{i \geq 0} \phi(i) Q(i, j) = - \lambda_j \phi(j) + \lambda_{j-1} \phi(j-1) = 0$

However, this brings us a new issue that the statement after this math expression, "It follows that $\phi$ is constant on $\mathbb Z_+$.", may not hold.
- This statement holds if we consider a special case of the pure birth process: when $\lambda_i=\lambda$ for all $i$.

It may require more discussion.

**Comment by jstac** [comment]
Thanks @shlff , this is very helpful.  We will need some mild conditions on the lambda sequence.

(Are you able to propose something a bit weaker than the requirement that they are all constant?)

**Comment by shlff** [comment]
Thanks @jstac .

How about letting $\lambda_i = \phi(i)$ for all $i$?

**Comment by jstac** [comment]
Hi @shlff , this doesn't work because the point is to show that no stationary distribution exists for (P_t).

**Comment by shlff** [comment]
Thanks for your patient waiting, @jstac . I figured out that we can prove it by consider a [Yule process](https://en.wikipedia.org/wiki/Birth_process) $\lambda_i= \lambda i$ for all $i$, where $0<\lambda <\infty$.

Here is my updated proof:
- Suppose to the contrary that $\phi \in \mathscr D$ and $\phi Q = 0$.
- Then, for any $j \geq 1$, $$ (\phi Q)(j) = \sum_{i \geq 0} \phi(i) Q(i, j) = - \lambda_j \phi(j) + \lambda_{j-1} \phi(j-1) = 0$$
- Since $(\lambda_k)$ is a bounded sequence in $(0, \infty)$, $\lambda_j >0$ for any $j\geq1$.
- Therefore, it must be $\phi(j)=0$ for all $j$ or $ \lambda_j \phi(j) = \lambda_{j-1} \phi(j-1)$ for any $j\geq 1$.
- For the 2nd case, since $\lambda_i = \lambda i$, we have $j \phi(j) = (j-1) \phi(j-1)$ or equivalently, $\phi(j) = \frac{j-1}{j} \phi(j-1)$ for any $j \geq 1$.
- From the last equation, we obtain $\phi(j) = \frac{j-1}{j} \frac{j-2}{j-1} \cdots \frac{0}{1} \phi(0)= 0$.
- For both cases, $\sum \phi(j) = 0$, which contradicts with our assumption $\phi \in \mathscr D$.
