### ISSUE TITLE
Put toc on front page, add logo

### ISSUE THREAD

**Issue by jstac** [jstac/continuous_time_mcs#89]
Sorry to bother you again @mmcky , but would you mind to set up the front page to be more analogous to the other QE lectures?

It would be nice to have the QE logo and the table of contents on the front page.

Just now I shortened the text on intro.md so it will better fit the standard QE lecture format and the toc will be easily visible.

**Comment by mmcky** [comment]
Sure thing @jstac let me take a look now.
