### ISSUE TITLE
QE logo not showing up

### ISSUE THREAD

**Issue by jstac** [jstac/continuous_time_mcs#91]
Hi @mmcky , thanks for adding the logo and new index page with toc.

toc is showing up fine but I don't get the QE logo top right or "Powered by Jupyter Book" or "Back to top".

(All three elements on the top right of the page are missing.)

I built after merging your PR and upgrading `quantecon-book-theme` and `jupyter-book` via pip, just now.

Do you have any ideas?

**Comment by mmcky** [comment]
Hey @jstac could you try running 

jb clean <dir>

Or 

jb clean <dir> --all

To clear the cache after the software upgrade

**Comment by jstac** [comment]
Tried both to no effect `:-(`

**Comment by mmcky** [comment]
Hmm .... this is a confusing one. I can't see to replicate this one.

Can you try a `private` window in chrome?

**Comment by jstac** [comment]
You're a genius @mmcky `:-)`

The private window did the trick.
