### ISSUE TITLE
Add chapter and section numbers

### ISSUE THREAD

**Issue by jstac** [jstac/continuous_time_mcs#92]
@mmcky , would you mind to show me how to add chapter and section numbers, like the other lectures?

Right now the table of contents on https://jstac.github.io/continuous_time_mcs/intro.html is a bullet point list, unlike the other lectures.

**Comment by mmcky** [comment]
hey @jstac submitted the PR to enable the numbering. 

I will go through tomorrow and see if we need any additional config to produce the `pdf` via LaTeX also.
